version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_telco_churn
    volumes:
      - ./2.prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_telco_churn
    volumes:
      - grafana_storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    networks:
      - monitoring_net
    depends_on:
      - prometheus

  inference_api:
    build: .
    container_name: inference_api_telco
    ports:
      - "5001:5001"
      - "8000:8000"
    networks:
      - monitoring_net
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager_telco
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - monitoring_net

networks:
  monitoring_net:
    driver: bridge

volumes:
  grafana_storage: